# JDBC properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory
    username: springstudent
    password: springstudent
# Simple Spring Security
  security:
    user:
      name: scott
      password: scott

logging:
  level:
    org:
      springframework:
        security: DEBUG