spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory
    username: springstudent
    password: springstudent

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
