spring:
  # JDBC properties
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory
    username: springstudent
    password: springstudent
  # spring banner
  main:
    banner-mode: console # off

logging:
  level:
    # reduce logging level. set logging level to warn
    root: warn
    # add logging config sto display SQL statements
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace